/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct SignMessage SignMessage;
typedef struct SpeedMessage SpeedMessage;
typedef struct SoundMessage SoundMessage;
typedef struct OverlimitSpeedMessage OverlimitSpeedMessage;
typedef struct OtaTypeMessage OtaTypeMessage;
typedef struct RotateMessage RotateMessage;
typedef struct AdjustVolumeSoundMessage AdjustVolumeSoundMessage;
typedef struct AdjustScreenBrightMessage AdjustScreenBrightMessage;
typedef struct AdjustSettingMessage AdjustSettingMessage;


/* --- enums --- */


/* --- messages --- */

struct  SignMessage
{
  ProtobufCMessage base;
  uint32_t position_1;
  uint32_t position_2;
  uint32_t distance_2;
  uint32_t position_3;
  uint32_t distance_3;
};
#define SIGN_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sign_message__descriptor) \
    , 0, 0, 0, 0, 0 }


struct  SpeedMessage
{
  ProtobufCMessage base;
  uint32_t speed;
};
#define SPEED_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&speed_message__descriptor) \
    , 0 }


struct  SoundMessage
{
  ProtobufCMessage base;
  uint32_t sound_id;
};
#define SOUND_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sound_message__descriptor) \
    , 0 }


struct  OverlimitSpeedMessage
{
  ProtobufCMessage base;
  protobuf_c_boolean is_over_speed_limit;
};
#define OVERLIMIT_SPEED_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&overlimit_speed_message__descriptor) \
    , 0 }


struct  OtaTypeMessage
{
  ProtobufCMessage base;
  uint32_t type;
};
#define OTA_TYPE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ota_type_message__descriptor) \
    , 0 }


struct  RotateMessage
{
  ProtobufCMessage base;
  uint32_t rotate_type;
};
#define ROTATE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rotate_message__descriptor) \
    , 0 }


/*
 * 0 - 100 
 */
struct  AdjustVolumeSoundMessage
{
  ProtobufCMessage base;
  uint32_t volume;
};
#define ADJUST_VOLUME_SOUND_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&adjust_volume_sound_message__descriptor) \
    , 0 }


/*
 * 0 - 100
 */
struct  AdjustScreenBrightMessage
{
  ProtobufCMessage base;
  uint32_t bright_level;
};
#define ADJUST_SCREEN_BRIGHT_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&adjust_screen_bright_message__descriptor) \
    , 0 }


typedef enum {
  ADJUST_SETTING_MESSAGE__SETTING__NOT_SET = 0,
  ADJUST_SETTING_MESSAGE__SETTING_VOLUME_MSG = 1,
  ADJUST_SETTING_MESSAGE__SETTING_BRIGHT_MSG = 2,
  ADJUST_SETTING_MESSAGE__SETTING_ROTATE_MSG = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(ADJUST_SETTING_MESSAGE__SETTING__CASE)
} AdjustSettingMessage__SettingCase;

struct  AdjustSettingMessage
{
  ProtobufCMessage base;
  AdjustSettingMessage__SettingCase setting_case;
  union {
    AdjustVolumeSoundMessage *volume_msg;
    AdjustScreenBrightMessage *bright_msg;
    RotateMessage *rotate_msg;
  };
};
#define ADJUST_SETTING_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&adjust_setting_message__descriptor) \
    , ADJUST_SETTING_MESSAGE__SETTING__NOT_SET, {0} }


/* SignMessage methods */
void   sign_message__init
                     (SignMessage         *message);
size_t sign_message__get_packed_size
                     (const SignMessage   *message);
size_t sign_message__pack
                     (const SignMessage   *message,
                      uint8_t             *out);
size_t sign_message__pack_to_buffer
                     (const SignMessage   *message,
                      ProtobufCBuffer     *buffer);
SignMessage *
       sign_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sign_message__free_unpacked
                     (SignMessage *message,
                      ProtobufCAllocator *allocator);
/* SpeedMessage methods */
void   speed_message__init
                     (SpeedMessage         *message);
size_t speed_message__get_packed_size
                     (const SpeedMessage   *message);
size_t speed_message__pack
                     (const SpeedMessage   *message,
                      uint8_t             *out);
size_t speed_message__pack_to_buffer
                     (const SpeedMessage   *message,
                      ProtobufCBuffer     *buffer);
SpeedMessage *
       speed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   speed_message__free_unpacked
                     (SpeedMessage *message,
                      ProtobufCAllocator *allocator);
/* SoundMessage methods */
void   sound_message__init
                     (SoundMessage         *message);
size_t sound_message__get_packed_size
                     (const SoundMessage   *message);
size_t sound_message__pack
                     (const SoundMessage   *message,
                      uint8_t             *out);
size_t sound_message__pack_to_buffer
                     (const SoundMessage   *message,
                      ProtobufCBuffer     *buffer);
SoundMessage *
       sound_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sound_message__free_unpacked
                     (SoundMessage *message,
                      ProtobufCAllocator *allocator);
/* OverlimitSpeedMessage methods */
void   overlimit_speed_message__init
                     (OverlimitSpeedMessage         *message);
size_t overlimit_speed_message__get_packed_size
                     (const OverlimitSpeedMessage   *message);
size_t overlimit_speed_message__pack
                     (const OverlimitSpeedMessage   *message,
                      uint8_t             *out);
size_t overlimit_speed_message__pack_to_buffer
                     (const OverlimitSpeedMessage   *message,
                      ProtobufCBuffer     *buffer);
OverlimitSpeedMessage *
       overlimit_speed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   overlimit_speed_message__free_unpacked
                     (OverlimitSpeedMessage *message,
                      ProtobufCAllocator *allocator);
/* OtaTypeMessage methods */
void   ota_type_message__init
                     (OtaTypeMessage         *message);
size_t ota_type_message__get_packed_size
                     (const OtaTypeMessage   *message);
size_t ota_type_message__pack
                     (const OtaTypeMessage   *message,
                      uint8_t             *out);
size_t ota_type_message__pack_to_buffer
                     (const OtaTypeMessage   *message,
                      ProtobufCBuffer     *buffer);
OtaTypeMessage *
       ota_type_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ota_type_message__free_unpacked
                     (OtaTypeMessage *message,
                      ProtobufCAllocator *allocator);
/* RotateMessage methods */
void   rotate_message__init
                     (RotateMessage         *message);
size_t rotate_message__get_packed_size
                     (const RotateMessage   *message);
size_t rotate_message__pack
                     (const RotateMessage   *message,
                      uint8_t             *out);
size_t rotate_message__pack_to_buffer
                     (const RotateMessage   *message,
                      ProtobufCBuffer     *buffer);
RotateMessage *
       rotate_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rotate_message__free_unpacked
                     (RotateMessage *message,
                      ProtobufCAllocator *allocator);
/* AdjustVolumeSoundMessage methods */
void   adjust_volume_sound_message__init
                     (AdjustVolumeSoundMessage         *message);
size_t adjust_volume_sound_message__get_packed_size
                     (const AdjustVolumeSoundMessage   *message);
size_t adjust_volume_sound_message__pack
                     (const AdjustVolumeSoundMessage   *message,
                      uint8_t             *out);
size_t adjust_volume_sound_message__pack_to_buffer
                     (const AdjustVolumeSoundMessage   *message,
                      ProtobufCBuffer     *buffer);
AdjustVolumeSoundMessage *
       adjust_volume_sound_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   adjust_volume_sound_message__free_unpacked
                     (AdjustVolumeSoundMessage *message,
                      ProtobufCAllocator *allocator);
/* AdjustScreenBrightMessage methods */
void   adjust_screen_bright_message__init
                     (AdjustScreenBrightMessage         *message);
size_t adjust_screen_bright_message__get_packed_size
                     (const AdjustScreenBrightMessage   *message);
size_t adjust_screen_bright_message__pack
                     (const AdjustScreenBrightMessage   *message,
                      uint8_t             *out);
size_t adjust_screen_bright_message__pack_to_buffer
                     (const AdjustScreenBrightMessage   *message,
                      ProtobufCBuffer     *buffer);
AdjustScreenBrightMessage *
       adjust_screen_bright_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   adjust_screen_bright_message__free_unpacked
                     (AdjustScreenBrightMessage *message,
                      ProtobufCAllocator *allocator);
/* AdjustSettingMessage methods */
void   adjust_setting_message__init
                     (AdjustSettingMessage         *message);
size_t adjust_setting_message__get_packed_size
                     (const AdjustSettingMessage   *message);
size_t adjust_setting_message__pack
                     (const AdjustSettingMessage   *message,
                      uint8_t             *out);
size_t adjust_setting_message__pack_to_buffer
                     (const AdjustSettingMessage   *message,
                      ProtobufCBuffer     *buffer);
AdjustSettingMessage *
       adjust_setting_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   adjust_setting_message__free_unpacked
                     (AdjustSettingMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SignMessage_Closure)
                 (const SignMessage *message,
                  void *closure_data);
typedef void (*SpeedMessage_Closure)
                 (const SpeedMessage *message,
                  void *closure_data);
typedef void (*SoundMessage_Closure)
                 (const SoundMessage *message,
                  void *closure_data);
typedef void (*OverlimitSpeedMessage_Closure)
                 (const OverlimitSpeedMessage *message,
                  void *closure_data);
typedef void (*OtaTypeMessage_Closure)
                 (const OtaTypeMessage *message,
                  void *closure_data);
typedef void (*RotateMessage_Closure)
                 (const RotateMessage *message,
                  void *closure_data);
typedef void (*AdjustVolumeSoundMessage_Closure)
                 (const AdjustVolumeSoundMessage *message,
                  void *closure_data);
typedef void (*AdjustScreenBrightMessage_Closure)
                 (const AdjustScreenBrightMessage *message,
                  void *closure_data);
typedef void (*AdjustSettingMessage_Closure)
                 (const AdjustSettingMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sign_message__descriptor;
extern const ProtobufCMessageDescriptor speed_message__descriptor;
extern const ProtobufCMessageDescriptor sound_message__descriptor;
extern const ProtobufCMessageDescriptor overlimit_speed_message__descriptor;
extern const ProtobufCMessageDescriptor ota_type_message__descriptor;
extern const ProtobufCMessageDescriptor rotate_message__descriptor;
extern const ProtobufCMessageDescriptor adjust_volume_sound_message__descriptor;
extern const ProtobufCMessageDescriptor adjust_screen_bright_message__descriptor;
extern const ProtobufCMessageDescriptor adjust_setting_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
