/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   sign_message__init
                     (SignMessage         *message)
{
  static const SignMessage init_value = SIGN_MESSAGE__INIT;
  *message = init_value;
}
size_t sign_message__get_packed_size
                     (const SignMessage *message)
{
  assert(message->base.descriptor == &sign_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sign_message__pack
                     (const SignMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sign_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sign_message__pack_to_buffer
                     (const SignMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sign_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SignMessage *
       sign_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SignMessage *)
     protobuf_c_message_unpack (&sign_message__descriptor,
                                allocator, len, data);
}
void   sign_message__free_unpacked
                     (SignMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sign_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   speed_message__init
                     (SpeedMessage         *message)
{
  static const SpeedMessage init_value = SPEED_MESSAGE__INIT;
  *message = init_value;
}
size_t speed_message__get_packed_size
                     (const SpeedMessage *message)
{
  assert(message->base.descriptor == &speed_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t speed_message__pack
                     (const SpeedMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &speed_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t speed_message__pack_to_buffer
                     (const SpeedMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &speed_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SpeedMessage *
       speed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SpeedMessage *)
     protobuf_c_message_unpack (&speed_message__descriptor,
                                allocator, len, data);
}
void   speed_message__free_unpacked
                     (SpeedMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &speed_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sound_message__init
                     (SoundMessage         *message)
{
  static const SoundMessage init_value = SOUND_MESSAGE__INIT;
  *message = init_value;
}
size_t sound_message__get_packed_size
                     (const SoundMessage *message)
{
  assert(message->base.descriptor == &sound_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sound_message__pack
                     (const SoundMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sound_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sound_message__pack_to_buffer
                     (const SoundMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sound_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SoundMessage *
       sound_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SoundMessage *)
     protobuf_c_message_unpack (&sound_message__descriptor,
                                allocator, len, data);
}
void   sound_message__free_unpacked
                     (SoundMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sound_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   overlimit_speed_message__init
                     (OverlimitSpeedMessage         *message)
{
  static const OverlimitSpeedMessage init_value = OVERLIMIT_SPEED_MESSAGE__INIT;
  *message = init_value;
}
size_t overlimit_speed_message__get_packed_size
                     (const OverlimitSpeedMessage *message)
{
  assert(message->base.descriptor == &overlimit_speed_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t overlimit_speed_message__pack
                     (const OverlimitSpeedMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &overlimit_speed_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t overlimit_speed_message__pack_to_buffer
                     (const OverlimitSpeedMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &overlimit_speed_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
OverlimitSpeedMessage *
       overlimit_speed_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (OverlimitSpeedMessage *)
     protobuf_c_message_unpack (&overlimit_speed_message__descriptor,
                                allocator, len, data);
}
void   overlimit_speed_message__free_unpacked
                     (OverlimitSpeedMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &overlimit_speed_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sign_message__field_descriptors[5] =
{
  {
    "position_1",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignMessage, position_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_2",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignMessage, position_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance_2",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignMessage, distance_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_3",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignMessage, position_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance_3",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SignMessage, distance_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sign_message__field_indices_by_name[] = {
  2,   /* field[2] = distance_2 */
  4,   /* field[4] = distance_3 */
  0,   /* field[0] = position_1 */
  1,   /* field[1] = position_2 */
  3,   /* field[3] = position_3 */
};
static const ProtobufCIntRange sign_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor sign_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SignMessage",
  "SignMessage",
  "SignMessage",
  "",
  sizeof(SignMessage),
  5,
  sign_message__field_descriptors,
  sign_message__field_indices_by_name,
  1,  sign_message__number_ranges,
  (ProtobufCMessageInit) sign_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor speed_message__field_descriptors[1] =
{
  {
    "speed",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SpeedMessage, speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned speed_message__field_indices_by_name[] = {
  0,   /* field[0] = speed */
};
static const ProtobufCIntRange speed_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor speed_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SpeedMessage",
  "SpeedMessage",
  "SpeedMessage",
  "",
  sizeof(SpeedMessage),
  1,
  speed_message__field_descriptors,
  speed_message__field_indices_by_name,
  1,  speed_message__number_ranges,
  (ProtobufCMessageInit) speed_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sound_message__field_descriptors[1] =
{
  {
    "sound_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SoundMessage, sound_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sound_message__field_indices_by_name[] = {
  0,   /* field[0] = sound_id */
};
static const ProtobufCIntRange sound_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sound_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SoundMessage",
  "SoundMessage",
  "SoundMessage",
  "",
  sizeof(SoundMessage),
  1,
  sound_message__field_descriptors,
  sound_message__field_indices_by_name,
  1,  sound_message__number_ranges,
  (ProtobufCMessageInit) sound_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor overlimit_speed_message__field_descriptors[1] =
{
  {
    "is_over_speed_limit",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(OverlimitSpeedMessage, is_over_speed_limit),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned overlimit_speed_message__field_indices_by_name[] = {
  0,   /* field[0] = is_over_speed_limit */
};
static const ProtobufCIntRange overlimit_speed_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor overlimit_speed_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "OverlimitSpeedMessage",
  "OverlimitSpeedMessage",
  "OverlimitSpeedMessage",
  "",
  sizeof(OverlimitSpeedMessage),
  1,
  overlimit_speed_message__field_descriptors,
  overlimit_speed_message__field_indices_by_name,
  1,  overlimit_speed_message__number_ranges,
  (ProtobufCMessageInit) overlimit_speed_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
